### ISSUE TITLE
Supersede gulp-apply-template ?

### ISSUE THREAD

**Issue by anselmbradford** [straticjs/gulp-attach-to-template#4]
This repo references and commends https://www.npmjs.com/package/gulp-apply-template, which is fine, but I've opened https://github.com/zaim/gulp-apply-template/issues/4 and the more serious https://github.com/zaim/gulp-apply-template/issues/5 without any response. It looks like [the maintainer](https://github.com/zaim) has no public contributions in the past two years, so it appears abandoned. I'm thinking maybe the language in the readme here should be re-written a bit under the premise that gulp-apply-template is dead. Thoughts?

**Comment by strugee** [comment]
Yeah, I think you're right. I'll add a note - we can always revert if that project resumes.
